language: python
python:
  - "3.4"
  - "3.5"

install: 
  pip install -r requirements-test.txt
script: 
  - py.test --doctest-modules aptdetector tests
  - py.test --cov=aptdetector tests/ 
after_success:
  coveralls
